//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom_15.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicYour
    {
        public int Id { get; set; }
        public string TenDangNhap { get; set; }
        public int IdProduct { get; set; }
        public System.DateTime NgayMua { get; set; }
    
        public virtual Music Music { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
